parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Core\Persistence\Repository\ApiRickAndMorty\RickAndMortyApiRepository:
        arguments:
            $baseUri: '%env(resolve:RICK_AND_MORTY_BASE_URL)%'

    sentiment_analyzer:
        class: Sentiment\Analyzer

    App\Core\Persistence\Action\Web\Episode\GetRawSentimentForMessageAction:
        arguments:
            $analyzer: '@sentiment_analyzer'

when@test:
    services:
        fake_http_client:
            class: App\Tests\Application\FakeHttpClient

        App\Core\Persistence\Repository\ApiRickAndMorty\RickAndMortyApiRepository:
            arguments:
                $baseUri: '%env(resolve:RICK_AND_MORTY_BASE_URL)%'
                $httpClient: '@fake_http_client'
